; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG34058 DB	'OK', 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	??0MyClassA@@QAE@XZ				; MyClassA::MyClassA
PUBLIC	??1MyClassA@@QAE@XZ				; MyClassA::~MyClassA
PUBLIC	??0MyClassB@@QAE@XZ				; MyClassB::MyClassB
PUBLIC	??1MyClassB@@QAE@XZ				; MyClassB::~MyClassB
PUBLIC	??0MyClassC@@QAE@XZ				; MyClassC::MyClassC
PUBLIC	??1MyClassC@@QAE@XZ				; MyClassC::~MyClassC
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_c$ = -28						; size = 28
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 58
	push	ebp
	mov	ebp, esp
	sub	esp, 28					; 0000001cH
; Line 59
	lea	ecx, DWORD PTR _c$[ebp]
	call	??0MyClassC@@QAE@XZ			; MyClassC::MyClassC
; Line 60
	push	OFFSET $SG34058
	call	_printf
	add	esp, 4
; Line 61
	lea	ecx, DWORD PTR _c$[ebp]
	call	??1MyClassC@@QAE@XZ			; MyClassC::~MyClassC
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassC@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassC@@QAE@XZ PROC				; MyClassC::~MyClassC, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 47
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 48
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 8
	call	??1MyClassA@@QAE@XZ			; MyClassA::~MyClassA
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1MyClassB@@QAE@XZ			; MyClassB::~MyClassB
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassC@@QAE@XZ ENDP				; MyClassC::~MyClassC
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassC@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassC@@QAE@XZ PROC				; MyClassC::MyClassC, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 42
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0MyClassB@@QAE@XZ			; MyClassB::MyClassB
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 8
	call	??0MyClassA@@QAE@XZ			; MyClassA::MyClassA
; Line 41
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+20], 3
; Line 51
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+24], 33			; 00000021H
; Line 44
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassC@@QAE@XZ ENDP				; MyClassC::MyClassC
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassB@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassB@@QAE@XZ PROC				; MyClassB::~MyClassB, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 31
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 32
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassB@@QAE@XZ ENDP				; MyClassB::~MyClassB
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassB@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassB@@QAE@XZ PROC				; MyClassB::MyClassB, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 26
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 25
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 2
; Line 35
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+4], 22			; 00000016H
; Line 28
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassB@@QAE@XZ ENDP				; MyClassB::MyClassB
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassA@@QAE@XZ PROC				; MyClassA::~MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 14
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 15
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassA@@QAE@XZ ENDP				; MyClassA::~MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassA@@QAE@XZ PROC				; MyClassA::MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\RE054\RE054\RE054.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 8
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 1
; Line 18
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+4], 11			; 0000000bH
; Line 19
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+8], 111			; 0000006fH
; Line 11
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassA@@QAE@XZ ENDP				; MyClassA::MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 959
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 960
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 961
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 962
	mov	eax, DWORD PTR __Result$[ebp]
; Line 963
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
	push	ebp
	mov	ebp, esp
; Line 645
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 90
	push	ebp
	mov	ebp, esp
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
