; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE038\RE038\RE038.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG34018 DB	'abc', 00H, 'def', 0dH, 0aH, 09H, '  ', 0dH, 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
	ORG $+1
$SG34019 DB	'%s', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?str_trim@@YAPADPAD@Z				; str_trim
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_s$ = -16						; size = 14
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE038\RE038\RE038.cpp
; Line 24
	sub	esp, 16					; 00000010H
; Line 25
	mov	eax, DWORD PTR $SG34018+8
	movq	xmm0, QWORD PTR $SG34018
	mov	DWORD PTR _s$[esp+24], eax
	mov	ax, WORD PTR $SG34018+12
	mov	WORD PTR _s$[esp+28], ax
; Line 9
	lea	eax, DWORD PTR _s$[esp+16]
; Line 25
	movq	QWORD PTR _s$[esp+16], xmm0
; Line 9
	lea	edx, DWORD PTR [eax+1]
	npad	6
$LL15@main:
	mov	cl, BYTE PTR [eax]
	inc	eax
	test	cl, cl
	jne	SHORT $LL15@main
	sub	eax, edx
	je	SHORT $LN7@main
	lea	edx, DWORD PTR _s$[esp+eax+15]
	npad	1
$LL6@main:
	mov	cl, BYTE PTR [edx]
	test	cl, cl
	je	SHORT $LN7@main
; Line 11
	cmp	cl, 13					; 0000000dH
	je	SHORT $LN9@main
	cmp	cl, 10					; 0000000aH
	je	SHORT $LN9@main
	cmp	cl, 9
	je	SHORT $LN9@main
	cmp	cl, 32					; 00000020H
	jne	SHORT $LN7@main
$LN9@main:
; Line 13
	mov	BYTE PTR [edx], 0
	dec	edx
	sub	eax, 1
	jne	SHORT $LL6@main
$LN7@main:
; Line 27
	lea	eax, DWORD PTR _s$[esp+16]
	push	eax
	push	OFFSET $SG34019
	call	_printf
; Line 28
	xor	eax, eax
	add	esp, 24					; 00000018H
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_s$ = 8							; size = 4
?str_trim@@YAPADPAD@Z PROC				; str_trim
; File C:\Users\Zmrbak\source\repos\RE038\RE038\RE038.cpp
; Line 9
	mov	edx, DWORD PTR _s$[esp-4]
	mov	ecx, edx
	push	esi
	lea	esi, DWORD PTR [ecx+1]
	npad	6
$LL13@str_trim:
	mov	al, BYTE PTR [ecx]
	inc	ecx
	test	al, al
	jne	SHORT $LL13@str_trim
	sub	ecx, esi
	je	SHORT $LN15@str_trim
	dec	ecx
	mov	esi, 1
	add	ecx, edx
	sub	esi, edx
$LL4@str_trim:
	mov	al, BYTE PTR [ecx]
	test	al, al
	je	SHORT $LN15@str_trim
; Line 11
	cmp	al, 13					; 0000000dH
	je	SHORT $LN7@str_trim
	cmp	al, 10					; 0000000aH
	je	SHORT $LN7@str_trim
	cmp	al, 9
	je	SHORT $LN7@str_trim
	cmp	al, 32					; 00000020H
	jne	SHORT $LN15@str_trim
$LN7@str_trim:
; Line 13
	mov	BYTE PTR [ecx], 0
	dec	ecx
	lea	eax, DWORD PTR [esi+ecx]
	test	eax, eax
	jne	SHORT $LL4@str_trim
$LN15@str_trim:
; Line 21
	mov	eax, edx
	pop	esi
	ret	0
?str_trim@@YAPADPAD@Z ENDP				; str_trim
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	esi
; Line 960
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 645
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 962
	pop	esi
; Line 963
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 645
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
