; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE032\RE032\RE032.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG34016 DB	'%d', 0aH, 00H
$SG34017 DB	'12345', 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
	ORG $+1
$SG34018 DB	'%s', 0aH, 00H
$SG34019 DB	'%d', 0aH, 00H
$SG34020 DB	'%d', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?f2c@@YAHH@Z					; f2c
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
EXTRN	_atoi:PROC
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	_strcmp:PROC
EXTRN	_strcpy:PROC
EXTRN	_strlen:PROC
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_d$ = -24						; size = 4
_c$ = -20						; size = 4
_a$ = -16						; size = 4
_b$ = -12						; size = 4
_data$ = -8						; size = 4
_data2$ = -4						; size = 4
_argc$ = 8						; size = 4
_argv$ = 12						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE032\RE032\RE032.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	sub	esp, 24					; 00000018H
; Line 20
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR _argv$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	push	edx
	call	_atoi
	add	esp, 4
	mov	DWORD PTR _b$[ebp], eax
; Line 21
	mov	eax, DWORD PTR _b$[ebp]
	push	eax
	call	?f2c@@YAHH@Z				; f2c
	add	esp, 4
	mov	DWORD PTR _a$[ebp], eax
; Line 22
	mov	ecx, DWORD PTR _a$[ebp]
	push	ecx
	push	OFFSET $SG34016
	call	_printf
	add	esp, 8
; Line 24
	mov	DWORD PTR _data$[ebp], OFFSET $SG34017
; Line 25
	mov	edx, DWORD PTR _data$[ebp]
	push	edx
	mov	eax, 4
	shl	eax, 0
	mov	ecx, DWORD PTR _argv$[ebp]
	mov	edx, DWORD PTR [ecx+eax]
	push	edx
	call	_strcpy
	add	esp, 8
	mov	DWORD PTR _data2$[ebp], eax
; Line 26
	mov	eax, DWORD PTR _data2$[ebp]
	push	eax
	push	OFFSET $SG34018
	call	_printf
	add	esp, 8
; Line 28
	mov	ecx, DWORD PTR _data2$[ebp]
	push	ecx
	mov	edx, DWORD PTR _data$[ebp]
	push	edx
	call	_strcmp
	add	esp, 8
	mov	DWORD PTR _c$[ebp], eax
; Line 29
	mov	eax, DWORD PTR _c$[ebp]
	push	eax
	push	OFFSET $SG34019
	call	_printf
	add	esp, 8
; Line 31
	mov	ecx, DWORD PTR _data2$[ebp]
	push	ecx
	call	_strlen
	add	esp, 4
	mov	DWORD PTR _d$[ebp], eax
; Line 32
	mov	edx, DWORD PTR _d$[ebp]
	push	edx
	push	OFFSET $SG34020
	call	_printf
	add	esp, 8
; Line 33
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?f2c@@YAHH@Z
_TEXT	SEGMENT
_f$ = 8							; size = 4
?f2c@@YAHH@Z PROC					; f2c, COMDAT
; File C:\Users\Zmrbak\source\repos\RE032\RE032\RE032.cpp
; Line 8
	push	ebp
	mov	ebp, esp
; Line 9
	mov	eax, DWORD PTR _f$[ebp]
	sub	eax, 32					; 00000020H
	imul	eax, eax, 5
	cdq
	mov	ecx, 9
	idiv	ecx
; Line 10
	pop	ebp
	ret	0
?f2c@@YAHH@Z ENDP					; f2c
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 959
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 960
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 961
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 962
	mov	eax, DWORD PTR __Result$[ebp]
; Line 963
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
	push	ebp
	mov	ebp, esp
; Line 645
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 90
	push	ebp
	mov	ebp, esp
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
