; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?toupper_1@@YADD@Z				; toupper_1
PUBLIC	?toupper_2@@YADD@Z				; toupper_2
PUBLIC	?toupper_3@@YADD@Z				; toupper_3
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 56
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
?toupper_3@@YADD@Z PROC					; toupper_3
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 33
	mov	cl, BYTE PTR _c$[esp-4]
	lea	eax, DWORD PTR [ecx-97]
	cmp	al, 25					; 00000019H
	ja	SHORT $LN2@toupper_3
; Line 36
	and	cl, -33					; ffffffdfH
$LN2@toupper_3:
; Line 42
	mov	al, cl
	ret	0
?toupper_3@@YADD@Z ENDP					; toupper_3
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
?toupper_2@@YADD@Z PROC					; toupper_2
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 20
	mov	cl, BYTE PTR _c$[esp-4]
	lea	eax, DWORD PTR [ecx-97]
; Line 21
	cmp	al, 25					; 00000019H
	ja	SHORT $LN2@toupper_2
; Line 23
	lea	eax, DWORD PTR [ecx-32]
; Line 29
	ret	0
$LN2@toupper_2:
; Line 27
	mov	al, cl
; Line 29
	ret	0
?toupper_2@@YADD@Z ENDP					; toupper_2
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_c$ = 8							; size = 1
?toupper_1@@YADD@Z PROC					; toupper_1
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 8
	mov	cl, BYTE PTR _c$[esp-4]
	lea	eax, DWORD PTR [ecx-97]
	cmp	al, 25					; 00000019H
	ja	SHORT $LN2@toupper_1
; Line 10
	lea	eax, DWORD PTR [ecx-32]
; Line 16
	ret	0
$LN2@toupper_1:
; Line 14
	mov	al, cl
; Line 16
	ret	0
?toupper_1@@YADD@Z ENDP					; toupper_1
_TEXT	ENDS
END
