; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?toupper_1@@YADD@Z				; toupper_1
PUBLIC	?toupper_2@@YADD@Z				; toupper_2
PUBLIC	?toupper_3@@YADD@Z				; toupper_3
PUBLIC	main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
main	PROC
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 56
	xor	eax, eax
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
c$ = 8
?toupper_3@@YADD@Z PROC					; toupper_3
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 33
	lea	eax, DWORD PTR [rcx-97]
	cmp	al, 25
	ja	SHORT $LN2@toupper_3
; Line 36
	and	cl, -33					; ffffffffffffffdfH
$LN2@toupper_3:
; Line 42
	movzx	eax, cl
	ret	0
?toupper_3@@YADD@Z ENDP					; toupper_3
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
c$ = 8
?toupper_2@@YADD@Z PROC					; toupper_2
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 20
	lea	eax, DWORD PTR [rcx-97]
; Line 21
	cmp	al, 25
	ja	SHORT $LN2@toupper_2
; Line 23
	lea	eax, DWORD PTR [rcx-32]
; Line 29
	ret	0
$LN2@toupper_2:
; Line 27
	movzx	eax, cl
; Line 29
	ret	0
?toupper_2@@YADD@Z ENDP					; toupper_2
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
c$ = 8
?toupper_1@@YADD@Z PROC					; toupper_1
; File C:\Users\Zmrbak\source\repos\RE040\RE040\RE040.cpp
; Line 8
	lea	eax, DWORD PTR [rcx-97]
	cmp	al, 25
	ja	SHORT $LN2@toupper_1
; Line 10
	lea	eax, DWORD PTR [rcx-32]
; Line 16
	ret	0
$LN2@toupper_1:
; Line 14
	movzx	eax, cl
; Line 16
	ret	0
?toupper_1@@YADD@Z ENDP					; toupper_1
_TEXT	ENDS
END
