; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG33900 DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG33901 DB	'%f', 0aH, 00H
$SG33902 DB	'%f', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	?f_float@@YAMMM@Z				; f_float
PUBLIC	?f_double@@YANNN@Z				; f_double
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	__real@40091eb851eb851f
PUBLIC	__real@4010851eb851eb85
PUBLIC	__real@4048f5c3
PUBLIC	__real@408428f6
PUBLIC	__real@40a0dea52a12f22b
PUBLIC	__real@40a0dea540000000
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	__fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT __real@40a0dea540000000
CONST	SEGMENT
__real@40a0dea540000000 DQ 040a0dea540000000r	; 2159.32
CONST	ENDS
;	COMDAT __real@40a0dea52a12f22b
CONST	SEGMENT
__real@40a0dea52a12f22b DQ 040a0dea52a12f22br	; 2159.32
CONST	ENDS
;	COMDAT __real@408428f6
CONST	SEGMENT
__real@408428f6 DD 0408428f6r			; 4.13
CONST	ENDS
;	COMDAT __real@4048f5c3
CONST	SEGMENT
__real@4048f5c3 DD 04048f5c3r			; 3.14
CONST	ENDS
;	COMDAT __real@4010851eb851eb85
CONST	SEGMENT
__real@4010851eb851eb85 DQ 04010851eb851eb85r	; 4.13
CONST	ENDS
;	COMDAT __real@40091eb851eb851f
CONST	SEGMENT
__real@40091eb851eb851f DQ 040091eb851eb851fr	; 3.14
CONST	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 18
	push	OFFSET $SG33900
	call	_printf
; Line 21
	movsd	xmm0, QWORD PTR __real@40a0dea540000000
	push	ecx
	movsd	QWORD PTR [esp], xmm0
	push	OFFSET $SG33901
	call	_printf
; Line 24
	movsd	xmm0, QWORD PTR __real@40a0dea52a12f22b
	add	esp, 4
	movsd	QWORD PTR [esp], xmm0
	push	OFFSET $SG33902
	call	_printf
	add	esp, 12					; 0000000cH
; Line 25
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 8
tv128 = 16						; size = 8
_b$ = 16						; size = 8
?f_double@@YANNN@Z PROC					; f_double
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 12
	movsd	xmm0, QWORD PTR _a$[esp-4]
	divsd	xmm0, QWORD PTR __real@40091eb851eb851f
	movsd	xmm2, QWORD PTR _b$[esp-4]
	mulsd	xmm2, QWORD PTR __real@4010851eb851eb85
	addsd	xmm2, xmm0
	subsd	xmm2, QWORD PTR _a$[esp-4]
	movsd	QWORD PTR tv128[esp-4], xmm2
	fld	QWORD PTR tv128[esp-4]
; Line 13
	ret	0
?f_double@@YANNN@Z ENDP					; f_double
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
tv128 = 8						; size = 4
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?f_float@@YAMMM@Z PROC					; f_float
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 7
	movss	xmm2, DWORD PTR _a$[esp-4]
	divss	xmm2, DWORD PTR __real@4048f5c3
	movss	xmm0, DWORD PTR _b$[esp-4]
	mulss	xmm0, DWORD PTR __real@408428f6
	addss	xmm2, xmm0
	subss	xmm2, DWORD PTR _a$[esp-4]
	movss	DWORD PTR tv128[esp-4], xmm2
	fld	DWORD PTR tv128[esp-4]
; Line 8
	ret	0
?f_float@@YAMMM@Z ENDP					; f_float
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	esi
; Line 960
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 645
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 962
	pop	esi
; Line 963
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 645
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
