; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG33014 DB	'Hello World!', 0aH, 00H
	ORG $+2
$SG33015 DB	'%f', 0aH, 00H
$SG33016 DB	'%f', 0aH, 00H
CONST	ENDS
PUBLIC	__local_stdio_printf_options
PUBLIC	_vfprintf_l
PUBLIC	printf
PUBLIC	?f_float@@YAMMM@Z				; f_float
PUBLIC	?f_double@@YANNN@Z				; f_double
PUBLIC	main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	__real@40091eb851eb851f
PUBLIC	__real@4010851eb851eb85
PUBLIC	__real@4048f5c3
PUBLIC	__real@405edccccccccccd
PUBLIC	__real@4080f9ae147ae148
PUBLIC	__real@408428f6
PUBLIC	__real@42f6e666
PUBLIC	__real@4407cd71
EXTRN	__acrt_iob_func:PROC
EXTRN	__stdio_common_vfprintf:PROC
EXTRN	_fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN3
	DD	imagerel $LN3+67
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$printf DD imagerel $LN3
	DD	imagerel $LN3+87
	DD	imagerel $unwind$printf
pdata	ENDS
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+126
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT __real@4407cd71
CONST	SEGMENT
__real@4407cd71 DD 04407cd71r			; 543.21
CONST	ENDS
;	COMDAT __real@42f6e666
CONST	SEGMENT
__real@42f6e666 DD 042f6e666r			; 123.45
CONST	ENDS
;	COMDAT __real@408428f6
CONST	SEGMENT
__real@408428f6 DD 0408428f6r			; 4.13
CONST	ENDS
;	COMDAT __real@4080f9ae147ae148
CONST	SEGMENT
__real@4080f9ae147ae148 DQ 04080f9ae147ae148r	; 543.21
CONST	ENDS
;	COMDAT __real@405edccccccccccd
CONST	SEGMENT
__real@405edccccccccccd DQ 0405edccccccccccdr	; 123.45
CONST	ENDS
;	COMDAT __real@4048f5c3
CONST	SEGMENT
__real@4048f5c3 DD 04048f5c3r			; 3.14
CONST	ENDS
;	COMDAT __real@4010851eb851eb85
CONST	SEGMENT
__real@4010851eb851eb85 DQ 04010851eb851eb85r	; 4.13
CONST	ENDS
;	COMDAT __real@40091eb851eb851f
CONST	SEGMENT
__real@40091eb851eb851f DQ 040091eb851eb851fr	; 3.14
CONST	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	06204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$printf DD 011801H
	DD	06218H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DD 011801H
	DD	06218H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 32
b$ = 40
main	PROC
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 17
$LN3:
	sub	rsp, 56					; 00000038H
; Line 18
	lea	rcx, OFFSET FLAT:$SG33014
	call	printf
; Line 20
	movss	xmm1, DWORD PTR __real@4407cd71
	movss	xmm0, DWORD PTR __real@42f6e666
	call	?f_float@@YAMMM@Z			; f_float
	movss	DWORD PTR a$[rsp], xmm0
; Line 21
	cvtss2sd xmm0, DWORD PTR a$[rsp]
	movaps	xmm1, xmm0
	movq	rdx, xmm1
	lea	rcx, OFFSET FLAT:$SG33015
	call	printf
; Line 23
	movsd	xmm1, QWORD PTR __real@4080f9ae147ae148
	movsd	xmm0, QWORD PTR __real@405edccccccccccd
	call	?f_double@@YANNN@Z			; f_double
	movsd	QWORD PTR b$[rsp], xmm0
; Line 24
	movsd	xmm1, QWORD PTR b$[rsp]
	movq	rdx, xmm1
	lea	rcx, OFFSET FLAT:$SG33016
	call	printf
; Line 25
	xor	eax, eax
	add	rsp, 56					; 00000038H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_double@@YANNN@Z PROC					; f_double
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 11
	movsd	QWORD PTR [rsp+16], xmm1
	movsd	QWORD PTR [rsp+8], xmm0
; Line 12
	movsd	xmm0, QWORD PTR a$[rsp]
	divsd	xmm0, QWORD PTR __real@40091eb851eb851f
	movsd	xmm1, QWORD PTR b$[rsp]
	mulsd	xmm1, QWORD PTR __real@4010851eb851eb85
	addsd	xmm0, xmm1
	subsd	xmm0, QWORD PTR a$[rsp]
; Line 13
	ret	0
?f_double@@YANNN@Z ENDP					; f_double
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
a$ = 8
b$ = 16
?f_float@@YAMMM@Z PROC					; f_float
; File C:\Users\Zmrbak\source\repos\RE011\RE011\RE011.cpp
; Line 6
	movss	DWORD PTR [rsp+16], xmm1
	movss	DWORD PTR [rsp+8], xmm0
; Line 7
	movss	xmm0, DWORD PTR a$[rsp]
	divss	xmm0, DWORD PTR __real@4048f5c3
	movss	xmm1, DWORD PTR b$[rsp]
	mulss	xmm1, DWORD PTR __real@408428f6
	addss	xmm0, xmm1
	subss	xmm0, DWORD PTR a$[rsp]
; Line 8
	ret	0
?f_float@@YAMMM@Z ENDP					; f_float
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT printf
_TEXT	SEGMENT
_Result$ = 32
_ArgList$ = 40
_Format$ = 64
printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+32], r9
	sub	rsp, 56					; 00000038H
; Line 959
	lea	rax, QWORD PTR _Format$[rsp+8]
	mov	QWORD PTR _ArgList$[rsp], rax
; Line 960
	mov	ecx, 1
	call	__acrt_iob_func
	mov	r9, QWORD PTR _ArgList$[rsp]
	xor	r8d, r8d
	mov	rdx, QWORD PTR _Format$[rsp]
	mov	rcx, rax
	call	_vfprintf_l
	mov	DWORD PTR _Result$[rsp], eax
; Line 961
	mov	QWORD PTR _ArgList$[rsp], 0
; Line 962
	mov	eax, DWORD PTR _Result$[rsp]
; Line 963
	add	rsp, 56					; 00000038H
	ret	0
printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _vfprintf_l
_TEXT	SEGMENT
_Stream$ = 64
_Format$ = 72
_Locale$ = 80
_ArgList$ = 88
_vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
$LN3:
	mov	QWORD PTR [rsp+32], r9
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 645
	call	__local_stdio_printf_options
	mov	rcx, QWORD PTR _ArgList$[rsp]
	mov	QWORD PTR [rsp+32], rcx
	mov	r9, QWORD PTR _Locale$[rsp]
	mov	r8, QWORD PTR _Format$[rsp]
	mov	rdx, QWORD PTR _Stream$[rsp]
	mov	rcx, QWORD PTR [rax]
	call	__stdio_common_vfprintf
; Line 646
	add	rsp, 56					; 00000038H
	ret	0
_vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __local_stdio_printf_options
_TEXT	SEGMENT
__local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	lea	rax, OFFSET FLAT:?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
__local_stdio_printf_options ENDP
_TEXT	ENDS
END
