; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE017\RE017\RE017.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG33892 DB	'Enter temperature in Fahrenheit:', 0aH, 00H
	ORG $+2
$SG33894 DB	'%d', 00H
	ORG $+1
$SG33895 DB	'Error while parsing your input!', 0aH, 00H
	ORG $+3
$SG33897 DB	'Error: Incorrect temperature!', 0aH, 00H
	ORG $+1
$SG33898 DB	'Celsius:%d', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	___local_stdio_scanf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	__vfscanf_s_l
PUBLIC	_scanf_s
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
PUBLIC	__real@c071126666666666
EXTRN	_exit:PROC
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	___stdio_common_vfscanf:PROC
EXTRN	__fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT __real@c071126666666666
CONST	SEGMENT
__real@c071126666666666 DQ 0c071126666666666r	; -273.15
CONST	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_fahrenheit$ = -4					; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE017\RE017\RE017.cpp
; Line 10
	push	ecx
; Line 14
	push	OFFSET $SG33892
	call	_printf
; Line 15
	lea	eax, DWORD PTR _fahrenheit$[esp+8]
	push	eax
	push	OFFSET $SG33894
	call	_scanf_s
	add	esp, 12					; 0000000cH
	cmp	eax, 1
	jne	SHORT $LN10@main
; Line 22
	mov	eax, DWORD PTR _fahrenheit$[esp+4]
	add	eax, -32				; ffffffe0H
; Line 24
	movsd	xmm0, QWORD PTR __real@c071126666666666
	lea	ecx, DWORD PTR [eax+eax*4]
	mov	eax, 954437177				; 38e38e39H
	imul	ecx
	sar	edx, 1
	mov	eax, edx
	shr	eax, 31					; 0000001fH
	add	eax, edx
	movd	xmm1, eax
	cvtdq2pd xmm1, xmm1
	comisd	xmm0, xmm1
	jbe	SHORT $LN3@main
; Line 26
	push	OFFSET $SG33897
	call	_printf
	add	esp, 4
; Line 32
	xor	eax, eax
	pop	ecx
	ret	0
$LN3@main:
; Line 31
	push	eax
	push	OFFSET $SG33898
	call	_printf
	add	esp, 8
; Line 32
	xor	eax, eax
	pop	ecx
	ret	0
$LN10@main:
; Line 17
	push	OFFSET $SG33895
	call	_printf
	add	esp, 4
; Line 18
	push	0
	call	_exit
$LN7@main:
	int	3
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _scanf_s
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_scanf_s PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 1319
	push	esi
; Line 1323
	mov	esi, DWORD PTR __Format$[esp]
	push	0
	call	___acrt_iob_func
	add	esp, 4
; Line 1096
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_scanf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vfscanf
	add	esp, 24					; 00000018H
; Line 1325
	pop	esi
; Line 1326
	ret	0
_scanf_s ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfscanf_s_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfscanf_s_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 1096
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_scanf_options
	mov	ecx, DWORD PTR [eax]
	push	DWORD PTR [eax+4]
	or	ecx, 1
	push	ecx
	call	___stdio_common_vfscanf
	add	esp, 24					; 00000018H
; Line 1099
	ret	0
__vfscanf_s_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT _printf
_TEXT	SEGMENT
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	esi
; Line 960
	mov	esi, DWORD PTR __Format$[esp]
	push	1
	call	___acrt_iob_func
	add	esp, 4
; Line 645
	lea	ecx, DWORD PTR __Format$[esp+4]
	push	ecx
	push	0
	push	esi
	push	eax
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 962
	pop	esi
; Line 963
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 645
	push	DWORD PTR __ArgList$[esp-4]
	push	DWORD PTR __Locale$[esp]
	push	DWORD PTR __Format$[esp+4]
	push	DWORD PTR __Stream$[esp+8]
	call	___local_stdio_printf_options
	push	DWORD PTR [eax+4]
	push	DWORD PTR [eax]
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_scanf_options
_TEXT	SEGMENT
___local_stdio_scanf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 102
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
; Line 103
	ret	0
___local_stdio_scanf_options ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
