; Listing generated by Microsoft (R) Optimizing Compiler Version 19.28.29915.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE017\RE017\RE017.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG33892 DB	'Enter temperature in Fahrenheit:', 0aH, 00H
	ORG $+2
$SG33894 DB	'%d', 00H
	ORG $+1
$SG33895 DB	'Error while parsing your input!', 0aH, 00H
	ORG $+3
$SG33897 DB	'Error: Incorrect temperature!', 0aH, 00H
	ORG $+1
$SG33898 DB	'Celsius:%d', 0aH, 00H
CONST	ENDS
PUBLIC	___local_stdio_printf_options
PUBLIC	___local_stdio_scanf_options
PUBLIC	__vfprintf_l
PUBLIC	_printf
PUBLIC	__vfscanf_s_l
PUBLIC	_scanf_s
PUBLIC	_main
PUBLIC	?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
PUBLIC	?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
PUBLIC	__real@c071126666666666
EXTRN	_exit:PROC
EXTRN	___acrt_iob_func:PROC
EXTRN	___stdio_common_vfprintf:PROC
EXTRN	___stdio_common_vfscanf:PROC
EXTRN	__fltused:DWORD
;	COMDAT ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_printf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA
_BSS	SEGMENT
?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA DQ 01H DUP (?) ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
_BSS	ENDS
;	COMDAT __real@c071126666666666
CONST	SEGMENT
__real@c071126666666666 DQ 0c071126666666666r	; -273.15
CONST	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_fahrenheit$ = -8					; size = 4
_celsius$ = -4						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE017\RE017\RE017.cpp
; Line 10
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 14
	push	OFFSET $SG33892
	call	_printf
	add	esp, 4
; Line 15
	lea	eax, DWORD PTR _fahrenheit$[ebp]
	push	eax
	push	OFFSET $SG33894
	call	_scanf_s
	add	esp, 8
	cmp	eax, 1
	je	SHORT $LN2@main
; Line 17
	push	OFFSET $SG33895
	call	_printf
	add	esp, 4
; Line 18
	push	0
	call	_exit
; Line 19
	xor	eax, eax
	jmp	SHORT $LN1@main
$LN2@main:
; Line 22
	mov	ecx, DWORD PTR _fahrenheit$[ebp]
	sub	ecx, 32					; 00000020H
	imul	eax, ecx, 5
	cdq
	mov	ecx, 9
	idiv	ecx
	mov	DWORD PTR _celsius$[ebp], eax
; Line 24
	cvtsi2sd xmm0, DWORD PTR _celsius$[ebp]
	movsd	xmm1, QWORD PTR __real@c071126666666666
	comisd	xmm1, xmm0
	jbe	SHORT $LN3@main
; Line 26
	push	OFFSET $SG33897
	call	_printf
	add	esp, 4
; Line 28
	xor	eax, eax
	jmp	SHORT $LN5@main
$LN3@main:
; Line 31
	mov	edx, DWORD PTR _celsius$[ebp]
	push	edx
	push	OFFSET $SG33898
	call	_printf
	add	esp, 8
$LN1@main:
; Line 32
	jmp	SHORT $LN6@main
$LN4@main:
	jmp	SHORT $LN5@main
$LN6@main:
	xor	eax, eax
$LN5@main:
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _scanf_s
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_scanf_s PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 1319
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 1322
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 1323
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	0
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfscanf_s_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 1324
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 1325
	mov	eax, DWORD PTR __Result$[ebp]
; Line 1326
	mov	esp, ebp
	pop	ebp
	ret	0
_scanf_s ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfscanf_s_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfscanf_s_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 1095
	push	ebp
	mov	ebp, esp
; Line 1096
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_scanf_options
	mov	ecx, DWORD PTR [eax]
	or	ecx, 1
	mov	edx, DWORD PTR [eax+4]
	push	edx
	push	ecx
	call	___stdio_common_vfscanf
	add	esp, 24					; 00000018H
; Line 1099
	pop	ebp
	ret	0
__vfscanf_s_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT _printf
_TEXT	SEGMENT
__Result$ = -8						; size = 4
__ArgList$ = -4						; size = 4
__Format$ = 8						; size = 4
_printf	PROC						; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 956
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 959
	lea	eax, DWORD PTR __Format$[ebp+4]
	mov	DWORD PTR __ArgList$[ebp], eax
; Line 960
	mov	ecx, DWORD PTR __ArgList$[ebp]
	push	ecx
	push	0
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	push	1
	call	___acrt_iob_func
	add	esp, 4
	push	eax
	call	__vfprintf_l
	add	esp, 16					; 00000010H
	mov	DWORD PTR __Result$[ebp], eax
; Line 961
	mov	DWORD PTR __ArgList$[ebp], 0
; Line 962
	mov	eax, DWORD PTR __Result$[ebp]
; Line 963
	mov	esp, ebp
	pop	ebp
	ret	0
_printf	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT __vfprintf_l
_TEXT	SEGMENT
__Stream$ = 8						; size = 4
__Format$ = 12						; size = 4
__Locale$ = 16						; size = 4
__ArgList$ = 20						; size = 4
__vfprintf_l PROC					; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h
; Line 644
	push	ebp
	mov	ebp, esp
; Line 645
	mov	eax, DWORD PTR __ArgList$[ebp]
	push	eax
	mov	ecx, DWORD PTR __Locale$[ebp]
	push	ecx
	mov	edx, DWORD PTR __Format$[ebp]
	push	edx
	mov	eax, DWORD PTR __Stream$[ebp]
	push	eax
	call	___local_stdio_printf_options
	mov	ecx, DWORD PTR [eax+4]
	push	ecx
	mov	edx, DWORD PTR [eax]
	push	edx
	call	___stdio_common_vfprintf
	add	esp, 24					; 00000018H
; Line 646
	pop	ebp
	ret	0
__vfprintf_l ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_scanf_options
_TEXT	SEGMENT
___local_stdio_scanf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 100
	push	ebp
	mov	ebp, esp
; Line 102
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_scanf_options@@9@4_KA ; `__local_stdio_scanf_options'::`2'::_OptionsStorage
; Line 103
	pop	ebp
	ret	0
___local_stdio_scanf_options ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ___local_stdio_printf_options
_TEXT	SEGMENT
___local_stdio_printf_options PROC			; COMDAT
; File C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_stdio_config.h
; Line 90
	push	ebp
	mov	ebp, esp
; Line 92
	mov	eax, OFFSET ?_OptionsStorage@?1??__local_stdio_printf_options@@9@4_KA ; `__local_stdio_printf_options'::`2'::_OptionsStorage
; Line 93
	pop	ebp
	ret	0
___local_stdio_printf_options ENDP
_TEXT	ENDS
END
