; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?f_signed@@YAHH@Z				; f_signed
PUBLIC	?f_unsigned@@YAII@Z				; f_unsigned
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 23
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
?f_unsigned@@YAII@Z PROC				; f_unsigned
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 17
	mov	eax, 954437177				; 38e38e39H
	mul	DWORD PTR _a$[esp-4]
	shr	edx, 1
	mov	eax, edx
; Line 18
	ret	0
?f_unsigned@@YAII@Z ENDP				; f_unsigned
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a$ = 8							; size = 4
?f_signed@@YAHH@Z PROC					; f_signed
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 10
	mov	eax, 954437177				; 38e38e39H
	imul	DWORD PTR _a$[esp-4]
	sar	edx, 1
	mov	eax, edx
	shr	eax, 31					; 0000001fH
	add	eax, edx
; Line 11
	ret	0
?f_signed@@YAHH@Z ENDP					; f_signed
_TEXT	ENDS
END
