; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?f_signed@@YAHH@Z				; f_signed
PUBLIC	?f_unsigned@@YAII@Z				; f_unsigned
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 17
	push	ebp
	mov	ebp, esp
; Line 19
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
?f_unsigned@@YAII@Z PROC				; f_unsigned
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 12
	push	ebp
	mov	ebp, esp
; Line 13
	mov	eax, DWORD PTR _a$[ebp]
	xor	edx, edx
	mov	ecx, 3
	div	ecx
; Line 14
	pop	ebp
	ret	0
?f_unsigned@@YAII@Z ENDP				; f_unsigned
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
?f_signed@@YAHH@Z PROC					; f_signed
; File C:\Users\Zmrbak\source\repos\RE030\RE030\RE030.cpp
; Line 7
	push	ebp
	mov	ebp, esp
; Line 8
	mov	eax, DWORD PTR _a$[ebp]
	cdq
	mov	ecx, 3
	idiv	ecx
; Line 9
	pop	ebp
	ret	0
?f_signed@@YAHH@Z ENDP					; f_signed
_TEXT	ENDS
END
