; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE028\RE028\RE028.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?f@@YAXPAH0I@Z					; f
PUBLIC	?f1@@YAXPAH0I@Z					; f1
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE028\RE028\RE028.cpp
; Line 31
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a1$ = 8						; size = 4
_a2$ = 12						; size = 4
_count$ = 16						; size = 4
?f1@@YAXPAH0I@Z PROC					; f1
; File C:\Users\Zmrbak\source\repos\RE028\RE028\RE028.cpp
; Line 18
	mov	ecx, DWORD PTR _count$[esp-4]
	mov	eax, 613566757				; 24924925H
	mul	ecx
	sub	ecx, edx
	shr	ecx, 1
	add	ecx, edx
	shr	ecx, 2
; Line 19
	test	ecx, ecx
	je	SHORT $LN3@f1
; Line 17
	mov	edx, DWORD PTR _a1$[esp-4]
	push	esi
	mov	esi, DWORD PTR _a2$[esp]
$LL4@f1:
; Line 22
	mov	eax, DWORD PTR [esi]
; Line 23
	lea	edx, DWORD PTR [edx+12]
	mov	DWORD PTR [edx-12], eax
; Line 24
	lea	esi, DWORD PTR [esi+28]
	sub	ecx, 1
	jne	SHORT $LL4@f1
	pop	esi
$LN3@f1:
; Line 26
	ret	0
?f1@@YAXPAH0I@Z ENDP					; f1
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_a1$ = 8						; size = 4
_a2$ = 12						; size = 4
_count$ = 16						; size = 4
?f@@YAXPAH0I@Z PROC					; f
; File C:\Users\Zmrbak\source\repos\RE028\RE028\RE028.cpp
; Line 8
	mov	ecx, DWORD PTR _count$[esp-4]
	mov	eax, 613566757				; 24924925H
	mul	ecx
	sub	ecx, edx
	shr	ecx, 1
	add	ecx, edx
	shr	ecx, 2
	test	ecx, ecx
	je	SHORT $LN3@f
	mov	edx, DWORD PTR _a1$[esp-4]
	push	esi
	mov	esi, DWORD PTR _a2$[esp]
$LL4@f:
; Line 10
	mov	eax, DWORD PTR [esi]
	lea	esi, DWORD PTR [esi+28]
	mov	DWORD PTR [edx], eax
	lea	edx, DWORD PTR [edx+12]
	sub	ecx, 1
	jne	SHORT $LL4@f
	pop	esi
$LN3@f:
; Line 12
	ret	0
?f@@YAXPAH0I@Z ENDP					; f
_TEXT	ENDS
END
