; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE026\RE026\RE026.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?from_ip@@YAIEEEE@Z				; from_ip
PUBLIC	?from_ip2@@YAIEEEE@Z				; from_ip2
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE026\RE026\RE026.cpp
; Line 21
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_ip1$ = 8						; size = 1
_ip2$ = 12						; size = 1
_ip3$ = 16						; size = 1
_ip4$ = 20						; size = 1
?from_ip2@@YAIEEEE@Z PROC				; from_ip2
; File C:\Users\Zmrbak\source\repos\RE026\RE026\RE026.cpp
; Line 13
	movzx	ecx, BYTE PTR _ip2$[esp-4]
	movzx	eax, BYTE PTR _ip1$[esp-4]
	add	ecx, 24					; 00000018H
	shl	eax, cl
	movzx	ecx, BYTE PTR _ip3$[esp-4]
	add	ecx, 16					; 00000010H
	shl	eax, cl
	movzx	ecx, BYTE PTR _ip4$[esp-4]
	add	ecx, 8
	shl	eax, cl
; Line 14
	ret	0
?from_ip2@@YAIEEEE@Z ENDP				; from_ip2
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_ip1$ = 8						; size = 1
_ip2$ = 12						; size = 1
_ip3$ = 16						; size = 1
_ip4$ = 20						; size = 1
?from_ip@@YAIEEEE@Z PROC				; from_ip
; File C:\Users\Zmrbak\source\repos\RE026\RE026\RE026.cpp
; Line 8
	movzx	eax, BYTE PTR _ip1$[esp-4]
	movzx	ecx, BYTE PTR _ip2$[esp-4]
	shl	eax, 8
	or	eax, ecx
	movzx	ecx, BYTE PTR _ip3$[esp-4]
	shl	eax, 8
	or	eax, ecx
	movzx	ecx, BYTE PTR _ip4$[esp-4]
	shl	eax, 8
	or	eax, ecx
; Line 9
	ret	0
?from_ip@@YAIEEEE@Z ENDP				; from_ip
_TEXT	ENDS
END
