; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG34014 DB	'1234', 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?atoi_1@@YAHPAD@Z				; atoi_1
PUBLIC	_main
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.cpp
; Line 24
	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
_TEXT	SEGMENT
_s$ = 8							; size = 4
?atoi_1@@YAHPAD@Z PROC					; atoi_1
; File C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.cpp
; Line 10
	mov	edx, DWORD PTR _s$[esp-4]
	xor	eax, eax
	push	ebx
	mov	bl, BYTE PTR [edx]
	test	bl, bl
	je	SHORT $LN3@atoi_1
	npad	3
$LL2@atoi_1:
; Line 14
	lea	ecx, DWORD PTR [eax+eax*4]
	movsx	eax, bl
	mov	bl, BYTE PTR [edx+1]
	lea	edx, DWORD PTR [edx+1]
	lea	eax, DWORD PTR [eax+ecx*2]
	add	eax, -48				; ffffffd0H
	test	bl, bl
	jne	SHORT $LL2@atoi_1
$LN3@atoi_1:
	pop	ebx
; Line 17
	ret	0
?atoi_1@@YAHPAD@Z ENDP					; atoi_1
_TEXT	ENDS
END
