; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG34014 DB	'1234', 00H
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	?atoi_1@@YAHPAD@Z				; atoi_1
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = -8						; size = 4
_data$ = -4						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.cpp
; Line 20
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 22
	mov	DWORD PTR _data$[ebp], OFFSET $SG34014
; Line 23
	mov	eax, DWORD PTR _data$[ebp]
	push	eax
	call	?atoi_1@@YAHPAD@Z			; atoi_1
	add	esp, 4
	mov	DWORD PTR _a$[ebp], eax
; Line 24
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_result$ = -4						; size = 4
_s$ = 8							; size = 4
?atoi_1@@YAHPAD@Z PROC					; atoi_1
; File C:\Users\Zmrbak\source\repos\RE031\RE031\RE031.cpp
; Line 7
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 8
	mov	DWORD PTR _result$[ebp], 0
$LN2@atoi_1:
; Line 10
	mov	eax, DWORD PTR _s$[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN3@atoi_1
; Line 14
	imul	edx, DWORD PTR _result$[ebp], 10
	mov	eax, DWORD PTR _s$[ebp]
	movsx	ecx, BYTE PTR [eax]
	lea	edx, DWORD PTR [edx+ecx-48]
	mov	DWORD PTR _result$[ebp], edx
	mov	eax, DWORD PTR _s$[ebp]
	add	eax, 1
	mov	DWORD PTR _s$[ebp], eax
; Line 15
	jmp	SHORT $LN2@atoi_1
$LN3@atoi_1:
; Line 16
	mov	eax, DWORD PTR _result$[ebp]
; Line 17
	mov	esp, ebp
	pop	ebp
	ret	0
?atoi_1@@YAHPAD@Z ENDP					; atoi_1
_TEXT	ENDS
END
