; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	??0MyClass@@QAE@XZ				; MyClass::MyClass
PUBLIC	??1MyClass@@QAE@XZ				; MyClass::~MyClass
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = -16						; size = 12
_a$ = -4						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 32
	push	ebp
	mov	ebp, esp
	sub	esp, 16					; 00000010H
; Line 33
	lea	ecx, DWORD PTR _o$[ebp]
	call	??0MyClass@@QAE@XZ			; MyClass::MyClass
; Line 34
	mov	DWORD PTR _a$[ebp], 12			; 0000000cH
; Line 35
	lea	ecx, DWORD PTR _o$[ebp]
	call	??1MyClass@@QAE@XZ			; MyClass::~MyClass
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClass@@QAE@XZ PROC					; MyClass::~MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 17
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 18
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClass@@QAE@XZ ENDP					; MyClass::~MyClass
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClass@@QAE@XZ PROC					; MyClass::MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 19
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 3
; Line 22
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+4], 1
; Line 13
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+8], 2
; Line 14
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClass@@QAE@XZ ENDP					; MyClass::MyClass
_TEXT	ENDS
END
