; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	??0MyClass@@QAE@XZ				; MyClass::MyClass
PUBLIC	??1MyClass@@QAE@XZ				; MyClass::~MyClass
PUBLIC	??0MyClassA@@QAE@XZ				; MyClassA::MyClassA
PUBLIC	??1MyClassA@@QAE@XZ				; MyClassA::~MyClassA
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = -8						; size = 4
_o$ = -4						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 41
	push	ebp
	mov	ebp, esp
	sub	esp, 8
; Line 42
	lea	ecx, DWORD PTR _o$[ebp]
	call	??0MyClassA@@QAE@XZ			; MyClassA::MyClassA
; Line 43
	mov	DWORD PTR _a$[ebp], 4
; Line 46
	lea	ecx, DWORD PTR _o$[ebp]
	call	??1MyClassA@@QAE@XZ			; MyClassA::~MyClassA
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassA@@QAE@XZ PROC				; MyClassA::~MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 28
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 29
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1MyClass@@QAE@XZ			; MyClass::~MyClass
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassA@@QAE@XZ ENDP				; MyClassA::~MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassA@@QAE@XZ PROC				; MyClassA::MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 23
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0MyClass@@QAE@XZ			; MyClass::MyClass
; Line 25
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassA@@QAE@XZ ENDP				; MyClassA::MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClass@@QAE@XZ PROC					; MyClass::~MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 13
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 14
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClass@@QAE@XZ ENDP					; MyClass::~MyClass
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClass@@QAE@XZ PROC					; MyClass::MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 9
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 16
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 1
; Line 11
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClass@@QAE@XZ ENDP					; MyClass::MyClass
_TEXT	ENDS
END
