; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30037.0 

	TITLE	C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

CONST	SEGMENT
?_Fake_alloc@std@@3U_Fake_allocator@1@B	ORG $+1		; std::_Fake_alloc
CONST	ENDS
PUBLIC	??0MyClass@@QAE@XZ				; MyClass::MyClass
PUBLIC	??1MyClass@@QAE@XZ				; MyClass::~MyClass
PUBLIC	??0MyClassA@@QAE@XZ				; MyClassA::MyClassA
PUBLIC	??1MyClassA@@QAE@XZ				; MyClassA::~MyClassA
PUBLIC	??0MyClassB@@QAE@XZ				; MyClassB::MyClassB
PUBLIC	??1MyClassB@@QAE@XZ				; MyClassB::~MyClassB
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_o$ = -28						; size = 24
_a$ = -4						; size = 4
_main	PROC
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 58
	push	ebp
	mov	ebp, esp
	sub	esp, 28					; 0000001cH
; Line 59
	lea	ecx, DWORD PTR _o$[ebp]
	call	??0MyClassB@@QAE@XZ			; MyClassB::MyClassB
; Line 60
	mov	DWORD PTR _a$[ebp], 24			; 00000018H
; Line 63
	lea	ecx, DWORD PTR _o$[ebp]
	call	??1MyClassB@@QAE@XZ			; MyClassB::~MyClassB
	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassB@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassB@@QAE@XZ PROC				; MyClassB::~MyClassB, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 44
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 45
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1MyClassA@@QAE@XZ			; MyClassA::~MyClassA
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassB@@QAE@XZ ENDP				; MyClassB::~MyClassB
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassB@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassB@@QAE@XZ PROC				; MyClassB::MyClassB, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 39
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0MyClassA@@QAE@XZ			; MyClassA::MyClassA
; Line 46
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+16], 3
; Line 48
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+20], 33			; 00000021H
; Line 41
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassB@@QAE@XZ ENDP				; MyClassB::MyClassB
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClassA@@QAE@XZ PROC				; MyClassA::~MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 29
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 30
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1MyClass@@QAE@XZ			; MyClass::~MyClass
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClassA@@QAE@XZ ENDP				; MyClassA::~MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClassA@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClassA@@QAE@XZ PROC				; MyClassA::MyClassA, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 24
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0MyClass@@QAE@XZ			; MyClass::MyClass
; Line 27
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+8], 2
; Line 33
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+12], 22			; 00000016H
; Line 26
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClassA@@QAE@XZ ENDP				; MyClassA::MyClassA
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??1MyClass@@QAE@XZ PROC					; MyClass::~MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 14
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 15
	mov	esp, ebp
	pop	ebp
	ret	0
??1MyClass@@QAE@XZ ENDP					; MyClass::~MyClass
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0MyClass@@QAE@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
??0MyClass@@QAE@XZ PROC					; MyClass::MyClass, COMDAT
; _this$ = ecx
; File C:\Users\Zmrbak\source\repos\REV052\REV052\REV052.cpp
; Line 10
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR _this$[ebp], ecx
; Line 9
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], 1
; Line 17
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+4], 11			; 0000000bH
; Line 12
	mov	eax, DWORD PTR _this$[ebp]
	mov	esp, ebp
	pop	ebp
	ret	0
??0MyClass@@QAE@XZ ENDP					; MyClass::MyClass
_TEXT	ENDS
END
